version: '3'

services:

  database:
    hostname: database
    build: './src/database'
    ports:
      - '5432:5432'

  app:
    hostname: app
    build: './src/app'
    volumes:
      - './src/app:/app'
    ports:
      - '8080:80'
    environment:
      - 'POSTGRES_PASSWORD:app'
      - 'POSTGRES_USER:app'
      - 'POSTGRES_DB:app'
