services:

  database:
    hostname: database
    build: './src/database'
    ports:
      - '5432:5432'

  laravel:
    hostname: laravel
    build: './src/laravel'
    volumes:
      - './src/laravel:/laravel'
    ports:
      - '8000:8000'
    environment:
      - 'POSTGRES_PASSWORD:laravel'
      - 'POSTGRES_USER:laravel'
      - 'POSTGRES_DB:laravel'
